name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2

      - name: Clean Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
